FROM node:slim

WORKDIR /app

COPY package*.json ./

RUN apt-get update

RUN apt-get install -y npm

COPY client .

EXPOSE 80

CMD ["npm", "install"]

CMD ["npm", "run", "build"]

CMD ["npm", "start"]