version: "3.9"
services:
  db:
    image: postgres:15
    container_name: vivid_db
    restart: always
    ports:
      - 5477:5432
    env_file:
      - .env
      - .env-non-dev
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: vivid_server
    command: sh -c "alembic upgrade head && python main.py"
    ports:
      - 8077:8077
    restart: always
    environment:
      - NODE_ENV=production
    env_file:
      - .env
      - .env-non-dev
    depends_on:
      - db
    volumes:
      - server_data:/app/data

  client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: vivid_client
    ports:
      - 80:3000
    restart: always
    environment:
      - NODE_ENV=production
      - REACT_APP_WEBSOCKET_PORT=8077
    env_file:
      - .env
      - .env-non-dev
#    volumes:
#      - client_data:/app/data


volumes:
  db_data:
  server_data:
#  client_data: