"""filename column in session model added

Revision ID: be96fb78c6e5
Revises: 7b68aa5a40eb
Create Date: 2023-12-10 14:57:16.442669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be96fb78c6e5'
down_revision = '7b68aa5a40eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('filename', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'filename')
    # ### end Alembic commands ###
